#
# use swift4,0
#
use_frameworks!

def shared_pods
  pod 'RealmSwift'
end

target ‘WCM_Realm’ do
  platform :ios, ‘11.4’
  shared_pods
end

target ‘WCM_Rwalm.watchkitapp’ do
  platform :watchos, ‘4.3’
  shared_pods
end

target ‘WCM_Rwalm.watchkitapp Extension’ do
  platform :watchos, ‘4.3’
  shared_pods
end

post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
end
